### ISSUE TITLE
sleeping 1s is (maybe) too small

### ISSUE THREAD

**Issue by mpavlase** [lubosmato/pipeliner#2]
Isn't sleeping for 1s in thread too often? The most precision resolution in whole project is one minute. Even if I consider some extra time to process the pipeline, I'd guess that 20s can be enough...
https://github.com/lubosmato/pipeliner/blob/abe866d81067ef03f6031adfe2decbce0f6d3954/pipeliner/pipeline_runner.py#L45

**Comment by lubosmato** [comment]
With one second interval for checking if a minute is transitioning it is guaranteed that a maximum delay is one second thus a pipeline is executed at a specific minute and 1 (or 0) second. If the interval was 20s the pipeline would have been executed in seconds range between 0-20.

For todays processors 1s interval for checking if minute is changing is no work at all.

There is a possible optimization to sleep for `60 - current_seconds` but I can't think of any use-case for applying this optimization 🙂.
