### ISSUE TITLE
send_message step - ideas

### ISSUE THREAD

**Issue by mpavlase** [lubosmato/pipeliner#5]
https://github.com/lubosmato/pipeliner/blob/abe866d81067ef03f6031adfe2decbce0f6d3954/pipeliner/steps/send_message.py#L17-L22

- `self._client` can be nice lazy-loading `@property`
- step name/module could tell you, that it's about **facebook** messages. It's not any generic message...

**Comment by lubosmato** [comment]
Good point with lazy-loading prop. Module `send_message.py` is intended to have multiple classes in future eg. SendMessageInstagram.
